idf_component_register(
    SRCS
        "main.c"
        "src/energyboxx_api.c"
        "src/wifi_provisioning.c"
        "src/wifi_web.c"
        "src/dns_server.c"
        "src/wifi_storage.c"
        "src/api_storage.c"
        "src/status_led.c"
        "src/uri_decode.c"
    INCLUDE_DIRS
        "."
        "inc"
    REQUIRES
        esp_wifi
        esp_event
        esp_netif
        nvs_flash
        esp_http_client
        esp_driver_gpio
        esp_http_server
        esp-tls
        mbedtls
        esp_timer
        led_strip
)